---
title: "COVID19, REPORTED CASES IN COLOMBIA OF CORONAVIRUS, 2020
  Source: INS https://www.ins.gov.co/Noticias/Paginas/Coronavirus.aspx"
author: "Marlon Ruiz"
output: flexdashboard::flex_dashboard

---
Column {data-width=600}
---

```{r}
library(leaflet)
library(DT)
library(ggplot2)
library(maptools)
DEPTOS<-readShapePoly("COVID19/SHAPES/INPUT/DEPTOS/DEPTOS")
```

```{r}
pal <- colorBin(
  palette = "YlOrRd", domain = DEPTOS$CASOS,
  bins = seq(0, max(DEPTOS$CASOS, na.rm = TRUE) + 10, by = 5)
)

DEPTOS$labels <- paste0(
  "<strong> Entidad Territorial: </strong> ",
  DEPTOS$DEPTO, "<br/> ",
  "<strong> COVID19: </strong> ",
  DEPTOS$CASOS, "<br/> "
) %>%
  lapply(htmltools::HTML)

leaflet(DEPTOS) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~ pal(CASOS),
    color = "white",
    fillOpacity = 0.7,
    label = ~labels,
    highlight = highlightOptions(
      color = "black",
      bringToFront = TRUE
    )
  ) %>%
  leaflet::addLegend(
    pal = pal, values = ~CASOS,
    opacity = 0.7, title = "CASOS"
  )
```
   

Column {data-width=400}
-------------------------------------

### Table


```{r}
DT::datatable(DEPTOS@data[, c("DEPTO","CASOS",               "GEN_F","GEN_M","VIRUS_I","VIRUS_R","EN_ESTU")],
              rownames = FALSE, options = list(pageLength = 10))

```   

### Histogram


```{r}
ggplot(data = DEPTOS@data, aes(x = CASOS)) + geom_histogram()
```